spring:
  application:
    name: one_you
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

# JWT Configuration
jwt:
  auth:
    converter:
      resource-id: one_you-api
      principal-attribute: preferred_username
