spring:
  application:
    name: one_you
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # 기본값: local
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# 서버 설정 (공통)
server:
  servlet:
    context-path: /api

# JWT Configuration (공통)
jwt:
  auth:
    converter:
      resource-id: one_you-api
      principal-attribute: preferred_username


# 공통 로깅 패턴
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

